import type { Unit } from "../types/types";

export const useFetchUnits = (): Unit[] => {
    return [
  { id: 0, description: "מטכ״ל", level: 0, simul: "0000", parentId: null, status: { id: 0, description: "בדיווח", visibility: "visible" } },

  { id: 1, description: "פיקוד צפון", level: 1, simul: "0001", parentId: 0, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 2, description: "פיקוד מרכז", level: 1, simul: "0002", parentId: 0, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 3, description: "פיקוד דרום", level: 1, simul: "0003", parentId: 0, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 4, description: "פיקוד העורף", level: 1, simul: "0004", parentId: 0, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 11, description: "אוגדה 11", level: 2, simul: "0011", parentId: 1, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 12, description: "אוגדה 12", level: 2, simul: "0012", parentId: 1, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 21, description: "אוגדה 21", level: 2, simul: "0021", parentId: 2, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 22, description: "אוגדה 22", level: 2, simul: "0022", parentId: 2, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 31, description: "אוגדה 31", level: 2, simul: "0031", parentId: 3, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 32, description: "אוגדה 32", level: 2, simul: "0032", parentId: 3, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 111, description: "חטיבה 111", level: 3, simul: "0111", parentId: 11, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 112, description: "חטיבה 112", level: 3, simul: "0112", parentId: 11, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 121, description: "חטיבה 121", level: 3, simul: "0121", parentId: 12, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 122, description: "חטיבה 122", level: 3, simul: "0122", parentId: 12, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 211, description: "חטיבה 211", level: 3, simul: "0211", parentId: 21, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 212, description: "חטיבה 212", level: 3, simul: "0212", parentId: 21, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 221, description: "חטיבה 221", level: 3, simul: "0221", parentId: 22, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 222, description: "חטיבה 222", level: 3, simul: "0222", parentId: 22, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 311, description: "חטיבה 311", level: 3, simul: "0311", parentId: 31, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 312, description: "חטיבה 312", level: 3, simul: "0312", parentId: 31, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 321, description: "חטיבה 321", level: 3, simul: "0321", parentId: 32, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 322, description: "חטיבה 322", level: 3, simul: "0322", parentId: 32, status: { id: 0, description: "בדיווח", visibility: "visible" } },

  { id: 1111, description: "גדוד 1111", level: 4, simul: "1111", parentId: 111, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 1112, description: "גדוד 1112", level: 4, simul: "1112", parentId: 111, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 1121, description: "גדוד 1121", level: 4, simul: "1121", parentId: 112, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 1122, description: "גדוד 1122", level: 4, simul: "1122", parentId: 112, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 1211, description: "גדוד 1211", level: 4, simul: "1211", parentId: 121, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 1212, description: "גדוד 1212", level: 4, simul: "1212", parentId: 121, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 1221, description: "גדוד 1221", level: 4, simul: "1221", parentId: 122, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 1222, description: "גדוד 1222", level: 4, simul: "1222", parentId: 122, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 2111, description: "גדוד 2111", level: 4, simul: "2111", parentId: 211, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 2112, description: "גדוד 2112", level: 4, simul: "2112", parentId: 211, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 2121, description: "גדוד 2121", level: 4, simul: "2121", parentId: 212, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 2122, description: "גדוד 2122", level: 4, simul: "2122", parentId: 212, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 2211, description: "גדוד 2211", level: 4, simul: "2211", parentId: 221, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 2212, description: "גדוד 2212", level: 4, simul: "2212", parentId: 221, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 2221, description: "גדוד 2221", level: 4, simul: "2221", parentId: 222, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 2222, description: "גדוד 2222", level: 4, simul: "2222", parentId: 222, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 3111, description: "גדוד 3111", level: 4, simul: "3111", parentId: 311, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 3112, description: "גדוד 3112", level: 4, simul: "3112", parentId: 311, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 3121, description: "גדוד 3121", level: 4, simul: "3121", parentId: 312, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 3122, description: "גדוד 3122", level: 4, simul: "3122", parentId: 312, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 3211, description: "גדוד 3211", level: 4, simul: "3211", parentId: 321, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 3212, description: "גדוד 3212", level: 4, simul: "3212", parentId: 321, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 3221, description: "גדוד 3221", level: 4, simul: "3221", parentId: 322, status: { id: 0, description: "בדיווח", visibility: "visible" } },
  { id: 3222, description: "גדוד 3222", level: 4, simul: "3222", parentId: 322, status: { id: 0, description: "בדיווח", visibility: "visible" } }
]
}